{% set name = "jupyter-vscode-proxy" %}
{% set version = "0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: 6d52db80f1505b95d63a40d4ed52cc73d19bf4d3285a9ab45c0ba7376f762cc8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - python >=3
    - jupyter-server-proxy
    - setuptools

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - jupyter_vscode_proxy

about:
  home: "https://github.com/betatim/vscode-binder"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "VS Code extension for Jupyter"

extra:
  recipe-maintainers:
    - xhochy
