{% set name = "jupyter-vscode-proxy" %}
{% set version = "0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 223f7ec2259234f8ad6e01d36a2f114e7baee48804e287b386ba588177dbec88

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - python >=3
    - jupyter-server-proxy
    - setuptools

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - jupyter_vscode_proxy

about:
  home: "https://github.com/betatim/vscode-binder"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "VS Code extension for Jupyter"

extra:
  recipe-maintainers:
    - xhochy
