{% set name = "jupyter-vscode-proxy" %}
{% set version = "0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: 60d365b608bb74d72695365e27a330469db73e58d863defb08c9d14fcd0d82d7

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - jupyter-server-proxy
    - setuptools

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - jupyter_vscode_proxy

about:
  home: "https://github.com/betatim/vscode-binder"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "VS Code extension for Jupyter"

extra:
  recipe-maintainers:
    - xhochy
